### ISSUE TITLE
Matplotlib/numpy issue inside RPI3 container

### ISSUE THREAD

**Issue by mo3rfan** [hamon-in/librtcdcpp#27]
```
root@black-pearl:/psl-librtcdcpp# python3 python/stress_test.py RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Traceback (most recent call last):  File "python/stress_test.py", line 10, in <module>
    import matplotlib.pyplot as plt  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar  File "/usr/local/lib/python3.6/dist-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist  File "/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py", line 16, in <module>
    from .path import Path
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/path.py", line 25, in <module>
    from . import _path, rcParams
ImportError: numpy.core.multiarray failed to import
```
Tried docker build with --no-cache.

Host OS: HypriotOS on RPI3
Docker version 17.11.0-ce, build 1caf76c

Saw a bunch of these during docker build: seccomp: config provided but seccomp not supported..

**Comment by mo3rfan** [comment]
Trying to build without default seccomp results in:

```
HypriotOS/armv7: pirate@black-pearl in ~/webrtc/librtcdcpp on master
$ docker build --no-cache --security-opt seccomp=unconfined -f Dockerfile-debian.armv7 -t librtcdcpp:latest .    
Error response from daemon: The daemon on this platform does not support setting security options on build
```
