### ISSUE TITLE
SIGILL @ rpi3 on alpine armhf container

### ISSUE THREAD

**Issue by mo3rfan** [hamon-in/librtcdcpp#28]
Commit: https://github.com/hamon-in/librtcdcpp/commit/4280238feee45e19ad085d0b46d7b032988a2f7b

## Warnings

- [x] Clear sentinel warnings in NiceWrapper.cpp https://github.com/hamon-in/librtcdcpp/commit/c85bb7997536cb5ff006b80c8d5118078ac44bda
- [x] Clear up format string warnings in librtcdcpp.cpp https://github.com/hamon-in/librtcdcpp/commit/49e67bcd0f2b04eb7813804fd1bab12e94aedd31
- [x] Clear up trampoline warnings in 2in1.c https://github.com/hamon-in/librtcdcpp/commit/819c115eaafb0ce936d08c4e4bf958591c011d44

**Comment by mo3rfan** [comment]
```
/psl-librtcdcpp # python3 python/stress_test.py
terminate called after throwing an instance of 'std::runtime_error'
  what():  Couldn't close file
Aborted (core dumped)
```

```
/psl-librtcdcpp/examples/websocket_client # ./2in1

====================++++10++

Process 12 exited with a coredump!!
```

**Comment by mo3rfan** [comment]
Debugging inside an alpine docker container with `--cap-add=SYS_PTRACE --security-opt seccomp=unconfined` [https://stackoverflow.com/a/46676907/679829](https://stackoverflow.com/a/46676907/679829)

```
(gdb) exec-file ./2in1
(gdb) core-file ./core
[New LWP 411]
[New LWP 386]
[New LWP 391]
[New LWP 383]
[New LWP 390]
[New LWP 412]
[New LWP 387]                                                   
[New LWP 418]                  
[New LWP 419]                                              
[New LWP 421]                                                  
[New LWP 422]                  
[New LWP 425]
[New LWP 426]                                                
[New LWP 431]                                              
[New LWP 432]
[New LWP 433]                                     
[New LWP 434]
[New LWP 435]                                                
[New LWP 436]
[New LWP 423]
[New LWP 437]
[New LWP 424]
[New LWP 438]
[New LWP 427]
[New LWP 429]
[New LWP 413]
[New LWP 428]
[New LWP 414]
[New LWP 430]
[New LWP 417]
[New LWP 415]
[New LWP 420]
[New LWP 416]
[New LWP 457]
warning: Can't read pathname for load map: No error information.
Core was generated by `./2in1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x76efb27c in __lookup_serv () from /lib/ld-musl-armhf.so.1
[Current thread is 1 (LWP 411)]
(gdb) bt
#0  0x76efb27c in __lookup_serv () at /lib/ld-musl-armhf.so.1
#1  0x76ef8084 in getaddrinfo () at /lib/ld-musl-armhf.so.1
(gdb) l
1       crt/arm/crti.s: No such file or directory.
(gdb) frame 1
#1  0x76ef8084 in getaddrinfo () from /lib/ld-musl-armhf.so.1
(gdb) l
1       in crt/arm/crti.s
```
 
GDB freezes when I try to run a program inside it. CPU goes to 100% and stays there. I was only able to inspect the crash via the coredump method above.

**Comment by mo3rfan** [comment]
Had to install debug symbols for musl, glib and libnice.

**Comment by mo3rfan** [comment]
![gdb](https://user-images.githubusercontent.com/705511/35319928-f27238de-0107-11e8-8618-973a164c1321.png)

This was on alpine docker container under x86.
